name: Cetus CI

on:
  push:
    branches:
      - master

jobs:
    run_ci_tests:
        name: Run Regression Tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install Dependencies
          uses: actions/setup-node@v2
          with:
            args: install
        - name: Clone Tests
          run: |
            git clone --recursive https://github.com/Qwokka/Cetus
            git clone https://github.com/Qwokka/CetusCITests
        - name: Install Dependencies
          run: |
            cd CetusCITests
            npm i
        - name: Run Tests
          uses: mujo-code/puppeteer-headful@16.6.0
          env:
            CI: "true"
          with:
            args: node CetusCITests/index.js -d Cetus/
